### ISSUE TITLE
2 Missing Projects from the ext\WITSML area

### ISSUE THREAD

**Issue by unixosgithub** [pds-technology/witsml-studio#2]
Visual Studio 2015 wasn't able to find the "Frameworks" and "Witsml" projects in the ext\Witsml folder as defined in the VS sln file.

Is it just me or really something actually missing ?

**Comment by bmdiaz** [comment]
Be sure to perform a --recursive clone when checking out the repository to include the submodule.  If downloading as a zip file, you will need to also download the witsml repository and copy the contents to the ext/witsml folder.

**Comment by unixosgithub** [comment]
That's it!. As Bobby suggested, I downloaded witsml repository zip file  and extacted it in the ext\witsml folder and everything worked fine.

Thanks Bobby.
