### ISSUE TITLE
The link to the license for witsml-studio returns 404

### ISSUE THREAD

**Issue by hwinkler** [pds-technology/witsml-studio#24]
http://www.pds.group/WITSMLstudio/OpenSource/ProductLicenseAgreement returns 404. I'd love to see what the license entails. Thanks.

**Comment by EricGriffith** [comment]
You can find it here:
https://pds.group/witsmlstudio/licence/

It's also included in the source:
https://github.com/pds-technology/witsml-studio/blob/master/LICENSE.txt
