### ISSUE TITLE
Core and Framework projects are missing from ext/witsml path

### ISSUE THREAD

**Issue by mayurlankeshwar** [pds-technology/witsml-studio#5]
Where can we find core and framework related projects? Solution not not compiling as these two projects are missing.

**Comment by bmdiaz** [comment]
If you downloaded the source code as a .zip file, you will need to also download the source code from the [witsml](https://github.com/pds-technology/witsml) repository and copy it to ext/witsml manually.  If you are cloning the witsml-studio repository to a local repository, make sure to recursively clone submodules as well.

**Comment by vinjain1012** [comment]
Do we have any command line support for witsml studio?
to be precise , getting results providing the URI of variables through command line.
