### ISSUE TITLE
Missing core and framework projects

### ISSUE THREAD

**Issue by deepaksinghalinfo** [pds-technology/witsml-studio#6]
Downloaded code is missing core and framework projects

![image](https://user-images.githubusercontent.com/32383722/45550165-ba255e00-b847-11e8-8acb-1c85c5471c24.png)

**Comment by EricGriffith** [comment]
Make sure you use a tool that recursively initializes git submodules.  These projects are included in the witsml repository, which is referred to from the witsml-studio repository as a submodule.  Visual Studio does not yet have good handling for submodules.
