### ISSUE TITLE
Service unavailable on website

### ISSUE THREAD

**Issue by GioPat** [pds-technology/witsml-studio#7]
I am warning you about the unavailability of the website that is lasting 2 weeks.
I am not able to install the software from the installer given that it tries to contact this host (I believe).

Is there the possibility to install the software given this scenario?

**Comment by bmdiaz** [comment]
Thank you for informing us about the unavailability of our Downloads site.  The issue has been resolved, please try again.

[https://witsml.pds.technology/docs/downloads/](https://witsml.pds.technology/docs/downloads/)
